# Post-fix coverage verification for vGCAMChina8.0
library(gcamreport)

gains_orig <- read.csv('E:/GCAM/GCAM_tools/gcam2gains/GCAM_GAINS_SEC_ACT_MAP.csv', stringsAsFactors=FALSE)
gains_target <- sort(unique(gains_orig$SOURCE_VARIABLE))

template <- get('template_vGCAMChina8.0')
template_vars <- unique(template$Variable)

# UPDATED alias mapping reflecting main.R changes (2026-04-30)
updated_alias_map <- list(
  # Ag Production - Livestock now produced directly from ag_production_map CSV
  # (CSV maps to GAINS names: Non-Energy|Livestock|Beef/Dairy/Pork/Poultry/SheepGoat)
  # Production|Chemicals|Fertilizer is now computed (Ammonia - N_Fertilizer * 17/14) in main.R
  # Land Cover (Crops + Otherarable now computed in get_land())
  'Land Cover|Forest' = 'Land Cover|Forest|Managed',
  'Land Cover|Pasture' = 'Land Cover|Pasture|Grazed',
  # Production (N Fertilizer removed - from production_map; Fertilizer now computed in main.R)
  'Production|Non-Metallic Minerals|Cement' = 'Production|Cement',
  # FE Steel - bridge Iron and Steel -> Steel naming
  'Final Energy|Industry|Iron and Steel|Gases' = 'Final Energy|Industry|Steel|Gases',
  'Final Energy|Industry|Iron and Steel|Liquids' = 'Final Energy|Industry|Steel|Liquids',
  'Final Energy|Industry|Iron and Steel|Electricity' = 'Final Energy|Industry|Steel|Electricity',
  'Final Energy|Industry|Iron and Steel|Solids|Coal' = 'Final Energy|Industry|Steel|Solids|Coal',
  # Off-road Construction (V8 uses 'Other Sector' naming for residual industry)
  'Final Energy|Industry|Other Sector|Electricity' = 'Final Energy|Industry|Off-road|Construction|Electricity',
  'Final Energy|Industry|Other Sector|Gases' = 'Final Energy|Industry|Off-road|Construction|Gases',
  'Final Energy|Industry|Other Sector|Hydrogen' = 'Final Energy|Industry|Off-road|Construction|Hydrogen',
  'Final Energy|Industry|Other Sector|Liquids' = 'Final Energy|Industry|Off-road|Construction|Liquids',
  # Primary Energy|*|Convert = Primary Energy|* (V8 doesn't split conversion separately)
  'Primary Energy|Biomass' = 'Primary Energy|Biomass|Convert',
  'Primary Energy|Coal' = 'Primary Energy|Coal|Convert',
  'Primary Energy|Gas' = 'Primary Energy|Gas|Convert',
  'Primary Energy|Oil' = c('Primary Energy|Oil|Convert', 'Primary Energy|Oil|Liquids'),
  # Final Energy "Other" categories (residual aggregation)
  'Final Energy|Industry|Other Sector' = c('Final Energy|Industry|Other',
                                           'Final Energy|Industry|Off-road|Construction'),
  'Final Energy|Residential and Commercial|Other' = 'Final Energy|Commercial|Others'
)

all_alias_targets <- unique(unlist(updated_alias_map))

# Variables that are dynamically generated by get_* functions (not in static maps)
dynamic_vars <- c(
  'Population',  # get_population()
  'GDP|MER',  # get_gdp_mer()
  # Primary Energy|Electricity|* generated by get_primary_energy_electricity()
  'Primary Energy|Electricity|Biomass|w/ CCS', 'Primary Energy|Electricity|Biomass|w/o CCS',
  'Primary Energy|Electricity|Coal|w/ CCS', 'Primary Energy|Electricity|Coal|w/o CCS',
  'Primary Energy|Electricity|Gas|w/ CCS', 'Primary Energy|Electricity|Gas|w/o CCS',
  'Primary Energy|Electricity|Geothermal', 'Primary Energy|Electricity|Hydro',
  'Primary Energy|Electricity|Nuclear', 'Primary Energy|Electricity|Oil|w/ CCS',
  'Primary Energy|Electricity|Oil|w/o CCS', 'Primary Energy|Electricity|Solar',
  'Primary Energy|Electricity|Wind'
)

# Collect statically mapped leaf vars
map_names <- c(
  'ag_production_map', 'ag_demand_map', 'land_use_map', 'production_map',
  'final_energy_map', 'primary_energy_map', 'res_extraction_map',
  'co2_sector_map', 'co2_resource_map', 'nonco2_emis_sector_map',
  'nonco2_emis_resource_map', 'kyoto_sector_map', 'carbon_seq_tech_map',
  'co2_tech_map', 'iron_steel_prod_tech_map',
  'transport_final_en_map', 'buildings_en_service', 'transport_en_service',
  'capacity_map', 'secondary_energy_map', 'water_map',
  'ag_demand_price_map', 'ag_price_map', 'en_demand_price_map',
  'energy_price_map', 'food_intake_map', 'food_items_map',
  'transport_sales_map', 'transport_stock_map', 'yield_map',
  'co2_ets_sector_map', 'co2_market_frag_map', 'conveyance.eff',
  'investment', 'iron_steel_trade_map', 'trade_ag', 'co2_market',
  'capital_gcam', 'carbon_content', 'cereal_scaler',
  'cf_gcam', 'cf_rgn', 'convert', 'iea_capacity',
  'region_mapping_ucd', 'ucd_core', 'ucd_size_class'
)

all_map_leaves <- character(0)
for(mn in map_names) {
  full_name <- paste0(mn, '_vGCAMChina8.0')
  obj <- try(get(full_name), silent=TRUE)
  if(!inherits(obj, 'try-error') && 'var' %in% names(obj)) {
    all_map_leaves <- c(all_map_leaves, unique(as.character(obj$var)))
  }
}
all_map_leaves <- unique(all_map_leaves[!is.na(all_map_leaves)])
all_map_leaves <- all_map_leaves[all_map_leaves != 'NoReported']

# Add vars produced by CSV-based maps (runtime-loaded)
csv_map_vars <- c(
  'Final Energy|Non-Energy Use|Gas',       # chemical feedstocks,gas
  'Final Energy|Non-Energy Use|Oil',       # chemical feedstocks,refined liquids
  'Final Energy|Non-Energy Use|Coal',      # chemical feedstocks,coal (fixed path)
  'Final Energy|Non-Energy Use|Biomass',   # chemical feedstocks,biomass (NEW)
  'Final Energy|Residential and Commercial|Other'  # produced by fe_sector_clean, in template
)

# Variables computed in functions.R (dedicated functions)
computed_vars <- c(
  'Land Cover|Cropland|Crops',        # sum of crop types from get_land()
  'Land Cover|Cropland|Otherarable',  # Cropland - Crops from get_land()
  'Feedstock|Industry|Steel|Coke',    # iron and steel coke feedstock from get_iron_steel_inputs()
  'Production|Chemicals|Fertilizer'   # Ammonia - N_Fertilizer * 17/14 computed in main.R
)

# Ag Production vars now directly produced from rebuilt ag_production_map (CSV source)
# (after package rebuild, these will be in all_map_leaves; listed here for pre-rebuild coverage)
ag_production_gains_vars <- c(
  'Agricultural Production|Non-Energy|Livestock|Beef',
  'Agricultural Production|Non-Energy|Livestock|Dairy',
  'Agricultural Production|Non-Energy|Livestock|Pork',
  'Agricultural Production|Non-Energy|Livestock|Poultry',
  'Agricultural Production|Non-Energy|Livestock|SheepGoat'
)

# Combine all known-good sources
known_good <- unique(c(all_map_leaves, csv_map_vars, dynamic_vars, computed_vars, ag_production_gains_vars))

# Also consider: variables in template that are ancestors of known-good vars
# (gather_map creates all ancestor hierarchy levels)
ancestor_vars <- character(0)
for(v in known_good) {
  parts <- strsplit(v, '\\|')[[1]]
  for(i in 1:(length(parts)-1)) {
    ancestor_vars <- c(ancestor_vars, paste(parts[1:i], collapse='|'))
  }
}
ancestor_vars <- unique(ancestor_vars)

# Final classification (accounting for updated aliases)
real_independent <- c()
real_with_alias_backup <- c()
alias_only <- c()
missing <- c()

for(v in gains_target) {
  in_known <- v %in% known_good
  in_template <- v %in% template_vars
  in_ancestor <- v %in% ancestor_vars
  is_alias <- v %in% all_alias_targets

  has_real <- in_known || (in_template && in_ancestor)

  if(has_real && !is_alias) {
    real_independent <- c(real_independent, v)
  } else if(has_real && is_alias) {
    real_with_alias_backup <- c(real_with_alias_backup, v)
  } else if(!has_real && is_alias) {
    alias_only <- c(alias_only, v)
  } else {
    missing <- c(missing, v)
  }
}

cat('===================================================\n')
cat('  POST-FIX GAINS COVERAGE FOR vGCAMChina8.0\n')
cat('===================================================\n\n')

cat(sprintf('Total GAINS targets: %d\n\n', length(gains_target)))

cat(sprintf('REAL independent (query data):   %2d (%.1f%%)\n', length(real_independent), 100*length(real_independent)/81))
cat(sprintf('REAL + alias backup:             %2d (%.1f%%)\n', length(real_with_alias_backup), 100*length(real_with_alias_backup)/81))
cat(sprintf('ALIAS only (proxy):              %2d (%.1f%%)\n', length(alias_only), 100*length(alias_only)/81))
cat(sprintf('MISSING:                         %2d (%.1f%%)\n', length(missing), 100*length(missing)/81))

cat(sprintf('\nREAL subtotal:                   %2d (%.1f%%)\n',
            length(real_independent)+length(real_with_alias_backup),
            100*(length(real_independent)+length(real_with_alias_backup))/81))

if(length(alias_only) > 0) {
  cat('\n--- ALIAS ONLY (no independent query data) ---\n')
  for(v in sort(alias_only)) {
    src <- names(Filter(function(x) v %in% x, updated_alias_map))
    cat(sprintf('  %-55s <- %s\n', v, src))
  }
}

if(length(missing) > 0) {
  cat('\n--- STILL MISSING ---\n')
  for(v in sort(missing)) cat(sprintf('  %s\n', v))
}

cat('\n=== CHANGES APPLIED ===\n')
cat('  main.R: Removed Steel tech alias (now from iron_steel_prod_tech_map)\n')
cat('  main.R: Removed N Fertilizer alias (now from production_map)\n')
cat('  main.R: Removed Land Cover Crops/Otherarable alias (now in get_land)\n')
cat('  main.R: Added Steel Electricity/Solids|Coal aliases\n')
cat('  main.R: Added Off-road Construction aliases using Other Sector source (corrected naming)\n')
cat('  main.R: Added Convert aliases (Biomass/Coal/Gas/Oil -> *|Convert)\n')
cat('  main.R: Added Primary Energy|Oil|Liquids alias\n')
cat('  main.R: Added FE Industry/R&C Other category aliases\n')
cat('  main.R: Fixed construction energy use source -> Other Sector (correct V8 naming)\n')
cat('  main.R: Fixed Commercial|Others alias direction (swapped source/target)\n')
cat('  final_energy_map_gcamchina.csv: Fixed Soilds->Solids typo\n')
cat('  final_energy_map_gcamchina.csv: Fixed coal feedstock path (removed Solids level)\n')
cat('  final_energy_map_gcamchina.csv: Added biomass feedstock mapping\n')
cat('  functions.R: Added Land Cover|Cropland|Otherarable = Cropland - Crops\n')
cat('  functions.R: Added get_iron_steel_inputs() for Feedstock|Industry|Steel|Coke (inputs by tech)\n')
cat('  variables_functions_mapping.csv: Added iron_steel_inputs_clean entry\n')
cat('  template_vGCAMChina8.0.rda: Fixed Internal_variable for Feedstock|Industry|Steel|Coke\n')
cat('  ag_production_map_vGCAMChina8.0.rda: Added Ruminant|Meat|Beef and |SheepGoat child entries\n')
cat('  template_vGCAMChina8.0.rda: Added Ruminant|Meat|Beef and |SheepGoat entries\n')
cat('  ag_production_map_vGCAMChina8.0.rda: Rebuilt from CSV with GAINS Non-Energy|Livestock names\n')
cat('  main.R: Removed 5 Ag Production aliases (now direct from ag_production_map)\n')
cat('  main.R: Beef/SheepGoat data split fixed (individual sectors, not shared total)\n')
cat('  main.R: Fertilizer computed as Ammonia - N_Fertilizer * 17/14 (not aliased from Ammonia)\n')
